# Generated by Django 3.2.6 on 2021-08-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=36)),
            ],
        ),
    ]
